### ISSUE TITLE
피처 엔지니어링, 제대로 시작하기

### ISSUE THREAD

**Issue by jehyunlee** [V-AIS/v-ais.github.io#22]
https://m.search.naver.com/search.naver?query=%ED%94%BC%EC%B2%98+%EC%97%94%EC%A7%80%EB%8B%88%EC%96%B4%EB%A7%81%2C+%EC%A0%9C%EB%8C%80%EB%A1%9C+%EC%8B%9C%EC%9E%91%ED%95%98%EA%B8%B0&sm=mtb_sug.top&where=m_book&oquery=%ED%94%BC%EC%B3%90+%EC%97%94%EC%A7%80%EB%8B%88%EC%96%B4%EB%A7%81&tqi=U4r1%2FlpySAsssvHDVQNssssssB4-378220&acq=%ED%94%BC%EC%B2%98&acr=1&qdt=0#api=%3F_lp_type%3Dcm%26col_prs%3Dcsa%26format%3Dtext%26nqx_theme%3D%257B%2B%2522theme%2522%253A%257B%2522main%2522%253A%257B%2522name%2522%253A%2522book_info%2522%252C%2522os%2522%253A14371200%252C%2522pkid%2522%253A20000%257D%257D%2B%257D%26query%3D%25ED%2594%25BC%25EC%25B2%2598%2B%25EC%2597%2594%25EC%25A7%2580%25EB%258B%2588%25EC%2596%25B4%25EB%25A7%2581%252C%2B%25EC%25A0%259C%25EB%258C%2580%25EB%25A1%259C%2B%25EC%258B%259C%25EC%259E%2591%25ED%2595%2598%25EA%25B8%25B0%26sm%3Digr_brg%26tab%3Dinfo%26tab_prs%3Dcsa%26where%3Dbridge&_lp_type=cm

**Comment by jjerry-k** [comment]
반영 완료!
