### ISSUE TITLE
케라스 창시자에게 배우는 딥러닝

### ISSUE THREAD

**Issue by Sihan-Son** [V-AIS/v-ais.github.io#26]
추천3
난이도2

기초 개념부터 프레임워크 전반에 대해 창시자가 직접 다루고 있어서 좋고, 번역자 운영하는 깃 리포가 현재 버전에 맞게 업데이트가 되어서 tf2.0에 케라스가 흡수된 지금도 괜찮은 서적

**Comment by jjerry-k** [comment]
반영 완료
